module.exports = {
  content: ["./src/app/**/*.{js,ts,jsx,tsx,mdx}", "./src/components/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        background: "rgb(var(--background-rgb) / <alpha-value>)",
        foreground: "rgb(var(--foreground-rgb) / <alpha-value>)",
        surface: "rgb(var(--surface-rgb) / <alpha-value>)",
        elevated: "rgb(var(--elevated-rgb) / <alpha-value>)",
        overlay: "rgb(var(--overlay-rgb) / <alpha-value>)",
        border: "rgb(var(--border-rgb) / <alpha-value>)",
        accent: "rgb(var(--accent-rgb) / <alpha-value>)",
        muted: "rgb(var(--muted-rgb) / <alpha-value>)",
        risk: "#DC2626",
        caution: "#D97706",
        clear: "#059669",
        info: "#2563EB",
        signal: {
          risk: "#DC2626",
          caution: "#D97706",
          clear: "#059669",
          info: "#2563EB",
        },
        aegis: {
          void: "rgb(var(--background-rgb) / <alpha-value>)",
          base: "rgb(var(--background-rgb) / <alpha-value>)",
          surface: "rgb(var(--surface-rgb) / <alpha-value>)",
          elevated: "rgb(var(--elevated-rgb) / <alpha-value>)",
          overlay: "rgb(var(--overlay-rgb) / <alpha-value>)",
          border: "rgb(var(--border-rgb) / 0.12)",
          "border-subtle": "rgb(var(--foreground-rgb) / 0.06)",
          text: "rgb(var(--foreground-rgb) / <alpha-value>)",
          muted: "rgb(var(--muted-rgb) / <alpha-value>)",
          dim: "rgb(var(--foreground-rgb) / 0.4)",
          accent: "rgb(var(--accent-rgb) / <alpha-value>)",
          "accent-muted": "rgb(var(--accent-rgb) / 0.82)",
          risk: "#DC2626",
          caution: "#D97706",
          clear: "#059669",
          info: "#2563EB",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
    },
  },
  plugins: [],
};
